// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGP98SV_mq-qOF0-FEW8kqQx4eUz8J6Rk',
    appId: '1:270276933005:web:413b1df63efb8610c779c4',
    messagingSenderId: '270276933005',
    projectId: 'metabolic-app-1f577',
    authDomain: 'metabolic-app-1f577.firebaseapp.com',
    storageBucket: 'metabolic-app-1f577.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfVggdNV2n-dZ_NydB6foapg55E1ulv4o',
    appId: '1:270276933005:android:7f72bac6461354eac779c4',
    messagingSenderId: '270276933005',
    projectId: 'metabolic-app-1f577',
    storageBucket: 'metabolic-app-1f577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq35SPfkEEO3wu6n0zEMgnjPeGZRn-fP4',
    appId: '1:270276933005:ios:e2774679b5cf496bc779c4',
    messagingSenderId: '270276933005',
    projectId: 'metabolic-app-1f577',
    storageBucket: 'metabolic-app-1f577.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq35SPfkEEO3wu6n0zEMgnjPeGZRn-fP4',
    appId: '1:270276933005:ios:58b235be89511765c779c4',
    messagingSenderId: '270276933005',
    projectId: 'metabolic-app-1f577',
    storageBucket: 'metabolic-app-1f577.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
